### ISSUE TITLE
figure out where `task.Timestamp` should be derived from

### ISSUE THREAD

**Issue by jorgemmsilva** [iotaledger/wasp#118]

**Comment by kape1395** [comment]
While there is a way to get the time from the L1 (https://docs.sui.io/guides/developer/sui-101/access-time), we probably don't have any requirement forcing us to use it.
  - Previously the transactions had requirements on timestamps (TX timestamp later than the requests consumed). Now that's not the case anymore.
  - The Clock object in SUI is a shared object. Thus, a query to it will cause a consensus round. I don't see why we need such an overhead.

So, my proposal is just to use the system time taken on each node as input to the consensus.
The consensus will take the highest of the proposed values, except the F highest (as it is done currently).
