### ISSUE TITLE
Apply new serialization framework to client libraries (wasp-cli, etc)

### ISSUE THREAD

**Issue by jorgemmsilva** [iotaledger/wasp#198]

**Comment by nnikolash** [comment]
On sprint planning we decided to postpone this task. It is not mandatory to do for the transition, so it has lower priority than any other actual part of MVP.

**Comment by lmoe** [comment]
At least for the wasp-cli we will sooner or later need it. :)
I'll add it for the sprint for this round as it's a very quick change.
